### PR TITLE
Fix accel

### PR DESCRIPTION
**Pull request by HarrisonGoldwyn**
This branch contains the 'more realistic' model for the bus velocity and acceleration based the following principles
- stopped at stops
- constant acceleration away and towards stops
- constant speed limit in between stops

The package is now capable of estimating the load profile (and total energy demand) on a defined bus route. An example of route 45 with 15% of points randomly assigned as points is included below (with default speed limit v_lim=15 m/s and acceleration constant a_m=1 m/s^2 and bus charging turned completely off).

Figure from `use_example__longi_dynam_model.ipynb`
image

Although I have tested all changes in the notebooks 'Writing_tests' (for simple_route with flat grade) and 'use_example__longi_dynam_model' (for real route 45), the unit tests should be expanded before this branch is pulled into the master. Let's keep this request open for another day while I finish that up. Please comment with any questions.

### CODE REVIEW

**Comment by HarrisonGoldwyn** [comment]
Just implemented what I am calling the 'bus mass per stop' feature. @EricaEgg and @ryancarlin0331 , please check out the new notebook `development_notebooks/use_example__loaded_bus_mass_per_stop.ipynb` for demonstration as to how this works

**Comment by EricaEgg** [comment]
image

Currently getting this error when running the mass_per_stop_instance command (line 8). Will see if I'm doing something wrong after lunch.

Thanks so much Harrison!

**Comment by HarrisonGoldwyn** [comment]
> Currently getting this error when running the mass_per_stop_instance command (line 8). Will see if I'm doing something wrong after lunch.

@EricaEgg, That is supposed to happen. My comments were not very clear, but that line and the next are tests to see that errors are raised when the inputs are not proper. You will notice in the line that the `stop_coords` contains 2 points while the `mass_array` contains three.

**Comment by EricaEgg** [comment]
@theomnipanda Oh ok. Thanks for the clarification! That makes sense

**Review by EricaEgg — COMMENTED** [review]
Looks ready to merge to me. 
I just noticed the y-axis of the load profile is mis-labeled, but I will fix that in the route_visualizer package. 
@theomnipanda Go ahead and merge when you have finished your unit tests

**Comment by ryancarlin0331** [comment]
Everything looks good. I am having trouble with the .tif file but working on that now. I read through the notebook and everything makes sense and discussed it with Erica.

Just kidding, it is fixed and working.

**Review by ryancarlin0331 — COMMENTED** [review]
Everything looks good! Thank you

**Pull request merged**
